use_frameworks!

target 'SenbayKit_Example' do
  pod 'SenbayKit', :path => '../'

  target 'SenbayKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
